baseURL = ""
languageCode = "en"
title = "Initio - Free, multipurpose html5 template by GetTemplate"
theme = "hugo-initio"

[params]
    name = "Aman"
    description = "A mystery person"
    email = "aman.kumar@gatisheel.com"
    phone = "+919986960111"
    address = "Gurgaon"
    year = 2023
    avatar = "images/aman.png"
    avatarclass = "circle"
    background = ""
    banner = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 10

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
